# Generated by Django 3.2.6 on 2021-08-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='custotchart',
            new_name='customchart',
        ),
        migrations.AlterField(
            model_name='coins',
            name='description',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='coins',
            name='logo',
            field=models.ImageField(blank=True, default='../static/images/icons/bitcoin.png', null=True, upload_to='logos'),
        ),
    ]
