# Generated by Django 3.2.6 on 2021-08-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210819_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='launchDate',
            field=models.DateTimeField(),
        ),
    ]
