# Generated by Django 3.2.6 on 2021-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coins_launchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='customchart',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='coins',
            name='discord',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
