# Generated by Django 3.2.6 on 2021-08-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210819_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='priceBNB',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='priceUSD',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
    ]
