# Generated by Django 3.2.6 on 2021-08-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_coins_registeredby'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='alltimebest',
            field=models.BooleanField(default=False),
        ),
    ]
