# Generated by Django 3.2.6 on 2021-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_coins_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='usercoin',
            field=models.BooleanField(default=True),
        ),
    ]
