# Generated by Django 3.2.6 on 2021-08-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coins_usercoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='launchDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='telegram',
            field=models.URLField(blank=True),
        ),
    ]
