# Generated by Django 3.2.6 on 2021-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210820_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='launchDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
