# Generated by Django 3.2.6 on 2021-08-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_coins_launchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='priceBNB',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=39, null=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='priceUSD',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=39, null=True),
        ),
    ]
