# Generated by Django 3.2.6 on 2021-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210820_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='priceBNB',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='priceUSD',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
    ]
