# Generated by Django 3.2.6 on 2021-08-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210820_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
