# Generated by Django 3.2.6 on 2021-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210820_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
