# Generated by Django 3.2.6 on 2021-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_coins_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
