# Generated by Django 3.2.6 on 2021-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_coins_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='priceBNB',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='priceUSD',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, max_length=100, null=True),
        ),
    ]
