# Generated by Django 3.2.6 on 2021-08-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_coins_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
