# Generated by Django 3.2.6 on 2021-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_coins_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coins',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coins',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
